// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIw0RiITmIhJO0DLvF0b9ghAtZ_vVeQZY',
    appId: '1:427382481427:web:6e45c8f9c904d726ae55e6',
    messagingSenderId: '427382481427',
    projectId: 'dev-fund-c10dd',
    authDomain: 'dev-fund-c10dd.firebaseapp.com',
    storageBucket: 'dev-fund-c10dd.firebasestorage.app',
    measurementId: 'G-RDHR0JZ3VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbYAWvPcYfeiQ2hUyH1uugXvv40zg6S0k',
    appId: '1:427382481427:android:b660a9f7c64ba9aaae55e6',
    messagingSenderId: '427382481427',
    projectId: 'dev-fund-c10dd',
    storageBucket: 'dev-fund-c10dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIsBJqezZTsgvYbvMttOlU2qBm4SFZ_kE',
    appId: '1:427382481427:ios:1fa4f08e9d4370dbae55e6',
    messagingSenderId: '427382481427',
    projectId: 'dev-fund-c10dd',
    storageBucket: 'dev-fund-c10dd.firebasestorage.app',
    iosBundleId: 'com.example.devFund',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIsBJqezZTsgvYbvMttOlU2qBm4SFZ_kE',
    appId: '1:427382481427:ios:1fa4f08e9d4370dbae55e6',
    messagingSenderId: '427382481427',
    projectId: 'dev-fund-c10dd',
    storageBucket: 'dev-fund-c10dd.firebasestorage.app',
    iosBundleId: 'com.example.devFund',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIw0RiITmIhJO0DLvF0b9ghAtZ_vVeQZY',
    appId: '1:427382481427:web:b2e20625760c214cae55e6',
    messagingSenderId: '427382481427',
    projectId: 'dev-fund-c10dd',
    authDomain: 'dev-fund-c10dd.firebaseapp.com',
    storageBucket: 'dev-fund-c10dd.firebasestorage.app',
    measurementId: 'G-VLB0YGXK45',
  );
}
